version: "3.7"
   
services:
  db:
    image: "postgres:11"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    command: gunicorn ratemyfrogs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/code/static/
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    volumes:
      - static:/code/static/
    ports:
      - 8008:80
    depends_on:
      - web


volumes:
    postgres_data:
    static:
