# Generated by Django 3.2 on 2021-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frog', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FrogRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingaverage', models.DecimalField(decimal_places=10, max_digits=15)),
                ('frog', models.ManyToManyField(to='ratings.Frog')),
            ],
        ),
    ]
