# Generated by Django 3.2.5 on 2021-07-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('total', models.PositiveIntegerField(default=0)),
                ('n', models.PositiveIntegerField(default=0)),
                ('notfrogs', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
