# Generated by Django 3.2.3 on 2021-06-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frog',
            name='id',
        ),
        migrations.AlterField(
            model_name='frog',
            name='url',
            field=models.URLField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
