# Generated by Django 3.2.5 on 2021-07-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frog',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
