# Generated by Django 3.2 on 2021-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='name',
            field=models.CharField(default='frog', max_length=200),
            preserve_default=False,
        ),
    ]
