# Generated by Django 3.2.3 on 2021-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20210627_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='notfrogs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
